### PR TITLE
general glean up of a few empty/useless files

### PR DESCRIPTION
**Pull request by GrapeLUX**
a lonely grape went out from the vine into the forest, burrowed into the ground and came out as the amazing grape we all know today as Dr Fried Rice

### CODE REVIEW

**Comment by nguyenhoangtran11** [comment]
Do not separate so many commits like that. One commit is enough

**Comment by GrapeLUX** [comment]
how would i pull them into a single comment?

**Comment by nguyenhoangtran11** [comment]
Please make all necessary changes into a commit and create another pull request

**Comment by giaki3003** [comment]
Don't worry @GrapeLUX you're doing just fine :+1:

**Pull request closed without merging**
